#!/usr/bin/env bash

set -e

dotfiles=(
  bin
  .scripts
  .bash_profile
  .bashrc
  .zshrc
  .tmux.conf
  .vim
  .vimrc
  .gitconfig
  .htoprc
  .irssi
)

# Symlink all dotfiles listed above to the right spot
for dotfile in ${dotfiles[@]}; do
  rm -f $HOME/$dotfile
  ln -sf $PWD/$dotfile $HOME/$dotfile
done

# Symlink NeoVim config in place
mkdir -p $HOME/.config
rm -f $HOME/.config/nvim
ln -sf $HOME/.vim $HOME/.config/nvim
