#!/usr/bin/env bash

set -e

dotfiles=(
  .irssi
  .scripts
  bin
  .bash_profile
  .bashrc
  .ghci
  .htoprc
  .prettierrc.yml
  .tmux.conf
  .config/alacritty/alacritty.yml
  .config/git/config
  .config/nvim
  .vimrc
  .zshrc
)

# Symlink all dotfiles listed above to the right spot
for dotfile in ${dotfiles[@]}; do
  rm -f $HOME/$dotfile
  mkdir -p $(dirname $HOME/$dotfile)
  ln -sf $PWD/$dotfile $HOME/$dotfile
done
