source ~/.scripts/common/util.sh
source ~/.scripts/common/path.sh
source ~/.scripts/common/exports.sh
source ~/.scripts/common/aliases.sh
source ~/.scripts/bash/prompt.sh
source ~/.scripts/bash/completions.sh
