Plug 'sheerun/vim-polyglot'
  let g:polyglot_disabled = ['typescript', 'typescript.tsx']
Plug 'jiangmiao/auto-pairs'
  let g:AutoPairsShortcutFastWrap = '<C-W>'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-endwise'
Plug 'godlygeek/tabular'
Plug 'vim-scripts/loremipsum'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'psliwka/vim-smoothie'
