# LogsAndDiagnostics.sh 
# This is a shell script to save logs&diagnostics for Pulse on Mac OS/X platforms.
# This also belongs to liblogsAndDiagnostics.a (in junsSDK), which provides a thin 
# static-lib wrapper for Pulse UI to call this script in a interruptible way and it
# also provides progress updates tp Pulse UI for display purposes. 


# Initializing...
echo 'Initializing...'
rm -f $1    # delete old file


# create temporary directory
rm -rf /tmp/JunosPulse
mkdir -p /tmp/JunosPulse/network

# Saving Diagnostics info...
echo 'Saving Diagnostics info...'
cd /tmp/JunosPulse/network; set > set.txt
cd /tmp/JunosPulse/network; ifconfig > ifconfig.txt
cd /tmp/JunosPulse/network; netstat -nra > netstat.txt
cd /tmp/JunosPulse/network; netstat -s > netstat-s.txt
cd /tmp/JunosPulse; zip "$1" network/*

# Saving Configuration files...
echo 'Saving Configuration files...'
cd /Applications/Junos\ Pulse.app/Contents/Plugins/; zip "$1" JUNS/access.ini
cd ~/Library/Application\ Support/Juniper\ Networks/; zip "$1" SetupClient/JuniperCompMgr.ini
cd $TMPDIR; zip "$1" SetupClient/*.manifest
cd /; zip "$1" tmp/pulse*    #capture manifest file generated by iveCM for component upgrade checking
cd /Library/Frameworks/; zip "$1" pulse.pac     #capture pulse.pac for proxy


# Saving Database files...
echo 'Saving Database files...'
cd /Library/Application\ Support/Juniper\ Networks/; zip "$1" Junos\ Pulse/*.dat


# Saving Version files...
echo 'Saving Version files...'
cd /Applications/Junos\ Pulse.app/Contents/; zip "$1" Resources/*Version.ini
cd /Applications/Junos\ Pulse.app/Contents/Plugins/; zip "$1" */versionInfo.ini


# Saving CrashDump files...
echo 'Saving CrashDump files...'
cd ~/Library/Logs/; zip "$1" DiagnosticReports/PulseTray*.crash; zip "$1" DiagnosticReports/Junos\ Pulse*.crash
cd ~/Library/Logs/; zip "$1" DiagnosticReports/jamCommand*.crash
cd ~/Library/Logs/; zip "$1" DiagnosticReports/JuniperSetupClient*.crash
cd ~/Library/Logs/; zip "$1" DiagnosticReports/HostChecker*.crash
cd /Library/Logs/; zip "$1" DiagnosticReports/dsAccessService*.crash
cd /Library/Logs/; zip "$1" DiagnosticReports/dsAccessService/*.crash


# Saving DebugLog files...
echo 'Saving DebugLog files...'
mkdir -p /tmp/JunosPulse/Logs/User
ln -sf /var/log/Juniper\ Networks/Logging/debuglog.log /tmp/JunosPulse/Logs/debuglog.log
ln -sf /var/log/Juniper\ Networks/Logging/debuglog.log.old /tmp/JunosPulse/Logs/debuglog.log.old
ln -sf /var/log/install.log /tmp/JunosPulse/Logs/install.log
ln -sf /var/log/system.log /tmp/JunosPulse/Logs/system.log
ln -sf /Library/Application\ Support/Juniper\ Networks/Junos\ Pulse/uninstall.log /tmp/JunosPulse/Logs/uninstall.log
ln -sf ~/Library/Logs/Juniper\ Networks/Logging/debuglog.log /tmp/JunosPulse/Logs/User/debuglog.log
ln -sf ~/Library/Logs/Juniper\ Networks/Logging/debuglog.log.old /tmp/JunosPulse/Logs/User/debuglog.log.old
ln -sf ~/Library/Logs/JuniperSetupExt.log /tmp/JunosPulse/Logs/User/JuniperSetupExt.log
cd /tmp/JunosPulse; zip -r "$1" Logs
rm -rf /tmp/JunosPulse

# Succeeded saving zip file: "$1"
echo 'Succeeded saving zip file: '"$1"
ls -l "$1"
