[tools]
go = "1.23.1"
ruby = "3.3.0"
node = "20.10.0"
python = "3.12.1"
java = "21.0.1"
erlang = "26.2.1"
elixir = "1.16.0"
haskell = "9.4.8"
elm = "0.19.1"
clojure = "1.11.1.1435"
leiningen = "2.10.0"
